version: '3.8'

services:
  # --- INFRASTRUCTURE SERVICES ---

  postgres:
    image: pgvector/pgvector:pg13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/

  # --- BACKEND MICROSERVICES ---

  auth:
    build:
      context: ../document-management-system
      dockerfile: ./apps/auth/Dockerfile
    container_name: auth_service
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    env_file:
      - .env

  users:
    build:
      context: ../document-management-system
      dockerfile: ./apps/users/Dockerfile
    container_name: users_service
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    env_file:
      - .env

  documents:
    build:
      context: ../document-management-system
      dockerfile: ./apps/documents/Dockerfile
    container_name: documents_service
    restart: always
    ports:
      - "3003:3003"
    depends_on:
      - postgres
    volumes:
      - ../document-management-system/uploads:/usr/src/app/uploads
    env_file:
      - .env

  ingestion:
    build:
      context: ../document-management-system
      dockerfile: ./apps/ingestion/Dockerfile
    container_name: ingestion_service
    restart: always
    ports:
      - "3004:3004"
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - .env

  # --- PYTHON RAG SERVICE ---
  
  rag_service:
    build:
      context: ../python-rag-service
      dockerfile: Dockerfile
    container_name: python_rag_service
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ../document-management-system/uploads:/app/uploads
    env_file:
      - .env

  # --- FRONTEND SERVICE ---

  frontend:
    build:
      context: ../document-management-frontend
      dockerfile: Dockerfile
    container_name: angular_frontend
    restart: always
    ports:
      - "4200:80"

volumes:
  postgres_data:
  rabbitmq_data:
